### ISSUE TITLE
IMPORTANT - type tag

### ISSUE THREAD

**Issue by franfranfranfran** [DanialStoica/prj-rev-bwfs-dasmoto#4]
https://github.com/DanialStoica/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L27
etc...

as far as i know, 'type' is not a valid html element. 

here is a complete list of possible html elements - https://www.w3schools.com/tags/

**Comment by DanialStoica** [comment]
I dont know what else to put because if I put <p> or <div> instead of "Type", then I wouldnt be able to get the last sentence to be directly under like it shows in the photo.
